kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64
  
steps:
- name: integration-test
  commands:
    - docker build -t dotnet-clean-architecture .
    - echo success
trigger:
  branch:
    - main
  event:
    - push
